### ISSUE TITLE
Use taints

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave-kube#1]
To make sure router continues to run on the master, we will need to use [`api.Taint`](https://godoc.org/k8s.io/kubernetes/pkg/api#Taint). This is a new way for labelling master nodes. We currently rely on implicit behaviour of DaemonSets getting scheduled on master(s) despite the `api.NodeSpec{Unschedulable: true}`. In my understanding all we will need to do is add an annotation to our DaemonSet.

See https://github.com/kubernetes/kubernetes/pull/31647 & https://github.com/kubernetes/kubernetes/issues/28687.

**Comment by mikedanese** [comment]
I don't event think you need to add an annotation. Daemonset will avoid taints on nodes unless they explicitly tolerate that taint so adding a taint to the master node should just take effect. IIUC, you don't want to run on the master?

**Comment by mikedanese** [comment]
Oops, ya. You will have to add a toleration to the metadata in the pod template.
