### ISSUE TITLE
Ensure netfilter bridging is enabled for correct kube-proxy operation

### ISSUE THREAD

**Issue by awh** [weaveworks/weave-kube#21]
Since weave-kube uses a bridge netdev, we need to make sure that br-nf is enabled so that k8s service DNAT works as intended:

`echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables`

This may entail loading the `br_netfilter` kernel module.

**Comment by bboreham** [comment]
Kubenet implementation: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/kubenet/kubenet_linux.go#L140-L150

**Comment by JustinAzoff** [comment]
I noticed that the commit for this does

```
if [ ! -f /proc/sys/net/bridge/bridge-nf-call-iptables ] ; then
    echo `/proc/sys/net/bridge/bridge-nf-call-iptables` not found >&2
    exit 1
fi 
```

Those are the wrong quotes and will cause something like

```
sh: /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
not found
```

Granted, it's already going to fail at that point, but the error will be a bit confusing.

**Comment by awh** [comment]
@JustinAzoff well spotted - thanks!
