### ISSUE TITLE
Merge weave-kube into weave repository

### ISSUE THREAD

**Issue by awh** [weaveworks/weave-kube#28]
- [x] Migrate code
- [x] Migrate issues
- [x] Integrate build into Makefile
- [x] Vendor dependencies
- [x] Update `bin/release`
- [x] Update release process as necessary

Supersedes #12, #13, #14, #15, #16.

**Comment by bboreham** [comment]
https://github.com/weaveworks/weave/pull/2551 migrates the code, Makefile, vendoring, release process

**Comment by bboreham** [comment]
Need to move weave-daemonset.yaml and the mapping of https://git.io/weave-kube ; looks like there is no API to do that - maybe GitHub support can do it?

**Comment by errordeveloper** [comment]
> maybe GitHub support can do it?

I've learned that it was not possible, I do recall speaking to someone and getting a NO. May be things changed, let's find out. I'd suggest hosting the URL at our domain.

**Comment by bboreham** [comment]
Where should we migrate the README?  A `site` page?

**Comment by awh** [comment]
Closed by weaveworks/weave#2581

**Comment by bboreham** [comment]
https://git.io/weave-kube migrated at around 18:40 UTC on 8th November
