### ISSUE TITLE
Make weave-kube work with AWSVPC mode

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave-kube#31]
This may be as simple as adding the flag, but will need testing, and all the setup preamble needs documenting.

**Comment by chrislovecnm** [comment]
@bboreham more details on this please

**Comment by bboreham** [comment]
https://www.weave.works/documentation/net-latest-using-weave/net-latest-awsvpc/

**Comment by chrislovecnm** [comment]
> The number of hosts in a cluster is limited by the maximum size of your AWS route table. This is limited to 50 entries though you can request an increase to 100 by contacting Amazon.

You want me to open another ticket about how to get around that??  That is a big concern of ours.

**Comment by bboreham** [comment]
We have spoken with Amazon; they do not have any plans to change it.  I guess it's down to performance; larger routing tables take time to scan.

The idea of working around the limit is noted at https://github.com/weaveworks/weave/issues/2322; I don't mind having a separate issue.

**Comment by chrislovecnm** [comment]
Did not ask a good question ;)  Can you run weave and get around the limit? Not run in aws vpc mode? Not sure if u have to use vpc mode.

**Comment by bboreham** [comment]
Yes, you can run in the default [overlay](https://www.weave.works/documentation/net-latest-how-it-works/net-latest-fastdp-how-it-works/) mode, where we don't set any limits on number of nodes.  No further configuration is required; this is the default.

AWSVPC mode is for people who want no overlay.

**Comment by chrislovecnm** [comment]
Perfect.  Any idea how much of a performance hit you get with the overlay?  I know native networking is always faster.

**Comment by bboreham** [comment]
As always with performance, you should measure the real system you care about.

However we posted some fairly simple benchmark numbers at https://www.weave.works/weave-fast-datapath/, and more graphically at https://www.weave.works/container-networking-no-overlay-aws-vpc/

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2611
