### ISSUE TITLE
Validating install

### ISSUE THREAD

**Issue by chrislovecnm** [weaveworks/weave-kube#33]
I am currently working on getting weave-kube running within an AWS VPCs.  Anything in particular with configuration or customizations?  For instance:

Does weave use CBR0 bridge?  I think no.
How do I verify that K8s is not creating VPC routing entries?
Anything about weave working with HA K8s that I need to consider?
Anything about weave with MTU that I should make sure that I configure?

**Comment by bboreham** [comment]
> Does weave use CBR0 bridge? I think no.

No; Weave Net creates its own bridge named `weave`

> How do I verify that K8s is not creating VPC routing entries?

Look in the route table in the AWS console?  Something like https://console.aws.amazon.com/vpc/home?region=us-east-1#routetables: (change region to suit)

> Anything about weave working with HA K8s that I need to consider?

Within one cluster I don't think HA changes anything. Weave Net will contact the active master on start-up, and from then on the communication comes kubelet->cni->Weave Net so the master isn't involved.

> Anything about weave with MTU that I should make sure that I configure?

Configuring the MTU is great for benchmarks; for real-world usage it's unlikely to be noticeable.  Whether you can even get a higher value to work depends on the exact AWS instances you are using and on the subnet they are connected to.

More importantly, the way the Weave Net overlay works means we only get to pick one MTU value for a given node, so it's best to stick with the lowest common denominator.
