### ISSUE TITLE
Make it easier for new users to find out what is broken

### ISSUE THREAD

**Issue by bboreham** [weaveworks/weave-kube#34]
E.g. if the underlying problem is a firewall or duplicate uuids, they have to go through some gyrations to find out.

Maybe we can fire an event which is picked up at the front end?

Maybe `kubeadm` should run a command which is a combination of `kubectl apply weave-kube` and listening for events?

@lukemarsden @errordeveloper any ideas?
#5 is somewhat related.

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2612
