### ISSUE TITLE
Activate weave encryption option for Kubernetes

### ISSUE THREAD

**Issue by nkratzke** [weaveworks/weave-kube#38]
It is great to activate Weave as an overlay network in Kubernetes just with one line.

   kubectl apply -f https://git.io/weave-kube

However, I wonder whether it is possible to activate the weave encryption option in Kubernetes in this setting?

Is it possible? What must be done?

**Comment by bboreham** [comment]
Weave Net encryption needs a shared secret (which we name the "password").  Presumably one would want to use [Kubernetes Secrets](http://kubernetes.io/docs/user-guide/secrets/)

Then one would modify the DaemonSet yaml to set the environment variable `WEAVE_PASSWORD` from this secret.

I haven't tried this yet.

**Comment by bboreham** [comment]
OK, I tried it; it seemed to work.

First create a file called `weave-passwd` with the secret password in it.  Then

```
$ kubectl create secret -n kube-system generic weave-passwd --from-file=./weave-passwd
```

Then modify the `weave-kube` daemonset as follows:

```
$ diff -c weave-daemonset.yaml weave-daemonset-password.yaml 
*** weave-daemonset.yaml    2016-10-17 11:16:31.723082390 +0000
--- weave-daemonset-password.yaml   2016-10-17 11:18:48.770925435 +0000
***************
*** 32,37 ****
--- 32,43 ----
                host: 127.0.0.1
                path: /status
                port: 6784
+           env:
+             - name: WEAVE_PASSWORD
+               valueFrom:
+                 secretKeyRef:
+                   name: weave-passwd
+                   key: weave-passwd
            securityContext:
              privileged: true
            volumeMounts:
```

**Comment by nkratzke** [comment]
Would it be possible to post a small code/config snippet?
Thank you very much.

Nane

Bryan Boreham notifications@github.com schrieb am Fr., 14. Okt. 2016 um
18:46 Uhr:

**Comment by bboreham** [comment]
Sure; see https://github.com/weaveworks/weave-kube/issues/38#issuecomment-253855874

**Comment by nkratzke** [comment]
I checked it. Worked! Maybe you should provide this as a standard option. And from my point of view: Weave should communicate the encryption feature more offensive.  I think weave is the only overlay network solution with integrated encryption (as far as I know).

However, this issue can be closed I think.

**Comment by totolitoto** [comment]
Tried it and the procedure is fine but I am not sure this actually encrypts the traffics between the nodes tcpdump still show all data in clear
Any suggestions welcome

**Comment by bboreham** [comment]
@totolitoto how exactly did you do the tcpdump?

**Comment by bboreham** [comment]
@totolitoto also could you check the logs of the `weave` container and see what it says about encryption. Maybe the configuration didn't work.

**Comment by totolitoto** [comment]
Thanks bboreham
I used tcpdump to inspect the traffic on the host outside the container and sniffed on the weave network interface like so 
So anything on the weave i/f to port 80 - that is where I have traffic flowing in and out ...
tcpdump -nneS -A -i weave port 80 

and I can see clear traffic text over the wire 

I will also check my logs

**Comment by awh** [comment]
Hi @totolitoto - the traffic is decrypted by the router before it hits the `weave` interface - this is why @bboreham asked exactly how you were doing the tcpdump. Packets between containers are only encrypted when they are travelling between weave peers - they get encapsulated in an encrypted UDP packet on port 6783.

**Comment by totolitoto** [comment]
ok @awh and @bboreham thanks for the clarification - makes sense.

**Comment by totolitoto** [comment]
I actually have a follow-up question here ...
What I am really interested in achieving is a fully encrypted communication in the data plane hence, is there a way to not have the router dencrypt/re-encrypt when travelling between weave peers?

Thanks in advance

**Comment by bboreham** [comment]
@totolitoto perhaps some confusion here: Weave Net only encrypts between peers; it decrypts when the data needs to be delivered to container interfaces. This maintains encryption on the wire without needing to alter the software sending or receiving the data.

Weave Net does not try to protect against someone with elevated privilege on the local machine who can sniff packets being delivered.

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2614
