### ISSUE TITLE
ARM compatibility ?

### ISSUE THREAD

**Issue by nlamirault** [weaveworks/weave-kube#44]
Hi
i've got a K8S master on RPI 3. I try to deploy weave-kube like that : 

```
$ sudo kubectl apply -f https://git.io/weave-kube
```

Containers crash. The logs : https://gist.github.com/nlamirault/01c4e8f52b6df68ec4c5cc50695f8be0

Do you have any ARM image ? Thanks.

**Comment by awh** [comment]
Hi @nlamirault - there are no ARM images at the moment, sorry!

**Comment by nlamirault** [comment]
OK. Thanks.
