### ISSUE TITLE
Network overlaps with existing route on host

### ISSUE THREAD

**Issue by crunchtime-ali** [weaveworks/weave-kube#48]
I am trying to setup a single node Kubernetes instance  using `kubeadm` and `kubectl` on a Ubuntu 16.04 host.
When choosing the network & policy I applied `kubectl apply -f https://git.io/weave-kube` but weave-net keeps erroring.

The result of `kubectl logs -c weave weave-net-ft9gj --namespace=kube-system` is:

```
Network 10.32.0.0/12 overlaps with existing route 10.42.0.0/16 on host.
```

How can I fix this?

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2736

**Comment by awh** [comment]
@dj-hedgehog we merged weave-kube into the main weave repo a while back - I have moved your issue there.
