### ISSUE TITLE
Document how to run 'weave status' command

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/weave-kube#5]
Given a k8s cluster with weave-kube installed, I'd like to be able to run `weave status` on each of the peers in the cluster, to inspect the health of the weave network. I believe this is possible with some `docker exec` or similar incantation, but it would be nice if this was documented in the README.

**Comment by bboreham** [comment]
I think it's `kubectl exec <weave pod name> /home/weave/weave --local status`

Alternatively, you can hit the /status url on any of the weave pods.  But I don't know how to do that via kubectl.

**Comment by Bregor** [comment]
`kubectl exec <weave pod name> --namespace=kube-system ...`

**Comment by bboreham** [comment]
Thanks @bregor !

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2603
